services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  tests:
    build:
      context: .
      dockerfile: docker/test.Dockerfile

