name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run test container
        run: docker-compose run --rm --build tests

      - name: Show test coverage summary
        run: |
          echo "===== Core Coverage ====="
          cat coveragereport/core/Summary.txt
          echo "===== API Coverage ====="
          cat coveragereport/api/Summary.txt

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coveragereport/

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build API Docker image
        run: docker build -f docker/api.Dockerfile -t taskmanager-api:latest .
